name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - src/**
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    #runs-on: [self-hosted, linux]
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装依赖项
        run: uv sync --frozen --no-dev

      - name: 运行测试
        run: |
          echo "No tests yet - running sanity check"
          uv run python -m http.server --help

      #- name: 构建Docker镜像
      #  run: docker build -t demo-python-devops

      - name: 登录DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 推送仓库
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: hoshien/demo-python-devops:latest
